# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Jayaram Hariharan"
title_separator          : "|"
name                     : "Jayaram Hariharan"
description              : "Jayaram Hariharan's personal website."
url                      : "https://jayaramhariharan.com"
#baseurl                  : "/minimal-mistakes"
repository               : "elbeejay/elbeejay.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs              : false # true, false (default)
words_per_minute         : 200
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : true
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : "HariharanJay"
og_image                 : "/assets/images/author.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://www.linkedin.com/in/jayaram-hariharan/"
    - "https://twitter.com/HariharanJay"
    - "https://github.com/elbeejay"
    - "https://fosstodon.org/@elbeejay"

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Jayaram Hariharan"
  avatar           : "/assets/images/author.png"
  bio              : "Civil Engineering PhD student at The University of Texas at Austin"
  location         :
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:jayaram.hariharan@utexas.edu
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elbeejay"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/HariharanJay"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: https://fosstodon.org/@elbeejay
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/jayaram-hariharan/"
    - label: "Curriculum Vitae (PDF)"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/files/jhariharan_resume.pdf"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:jayaram.hariharan@utexas.edu
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elbeejay"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/HariharanJay"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: https://fosstodon.org/@elbeejay
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/jayaram-hariharan/"
    - label: "Curriculum Vitae (PDF)"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/files/jhariharan_resume.pdf"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .gitignore
  - .idea
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "America/New_York"


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.md ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.md ~> path: /categories/
#  - <base_path/my-awesome-category/index.md ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


collections:
  research:
    output: true
    permalink: /:collection/:path/
  tidbits:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      read_time: false
      author_profile: true
      share: false
      comments: false
      sidebar:
        nav: "research"
  # _tidbits
  - scope:
      path: ""
      type: tidbits
    values:
      layout: single
      read_time: false
      author_profile: true
      share: false
      comments: false
      sidebar:
        nav: "tidbits"

# Mike (from https://github.com/sestus/mikemylonakis.com)
typed_lines:
  - text: "Hello and welcome to Jayaram's personal website!"
dynamic-typing: true
shuffle: true # Shuffle the lines.
loop: false
loop-count: false # Set False for infinite loop, or set any number for finite loop.
type-speed: 1
start-delay: 100
delete-delay: 5000

events:
- image: "/assets/images/timeline/RGB_CockrellSchoolLogo.png"
  date: "August 2017 - Present"
  description: "Environmental and water resources engineering graduate student at The University of Texas at Austin. Conducting computational research focused on understanding river delta subsurface composition from surface information"
- image: "/assets/images/timeline/GLW-Logo-White-Red-150x64.png"
  date: "January 2015 - July 2017"
  description: "Civil Engineer (Land Development Design) at GLW P.A., led the civil site design and approval processes for two commercial projects in Howard County, MD"
- image: "/assets/images/timeline/UMD_ENG_Left_Color_web.png"
  date: "August 2011 - December 2014"
  description: "Bachelor of Science in Civil and Environment Engineering - The University of Maryland at College Park"
- image: "/assets/images/timeline/Ardsley_Panthers_Logo.jpg"
  date: "June 2011"
  description: "Graduated from Ardsley High School, Ardsley, NY"

timeline-img: ""

after_footer_scripts:
  - /assets/js/mike.js
